[package]
name = "eva-asm"
description = "EVM assembly"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
strum.workspace = true

[lints]
workspace = true
