[package]
name = "oculars"
description = "EVM analysis toolkit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dasm = { workspace = true }
asm = { workspace = true }

[lints]
workspace = true
