[package]
name = "evanalyzer"
description = "EVM analysis toolkit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
eva-disassembler = { workspace = true }

[lints]
workspace = true
