[package]
name = "oculars-dasm"
description = "EVM disassembler"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
forks.workspace = true

[lints]
workspace = true
