[package]
name = "eva-dasm"
description = "EVM disassembler"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
