name: Format, Lint, Test & Build
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with: 
          components: clippy, rustfmt
          
      - name: Format
        run: cargo fmt --verbose --check
      - name: Lint
        run: cargo clippy --verbose -- -Dwarnings
      - name: Test
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
